name: Flutter CI (Frontend)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'  # Specify the desired Flutter SDK version

      - name: Change Directory to Frontend
        run: cd frontend

      - name: Install dependencies
        working-directory: frontend  # Specify the working directory
        run: flutter pub get  # Use 'flutter pub get' to install Flutter dependencies

      - name: Analyze project source
        working-directory: frontend  # Specify the working directory
        run: flutter analyze

      - name: Run tests
        working-directory: frontend  # Specify the working directory
        run: flutter test
