name: Dart CI (Frontend)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          dart-version: '2.18.2'  # Specify the desired Dart SDK version

      - name: Install dependencies
        working-directory: frontend  # Specify the working directory
        run: flutter pub get

      - name: Analyze project source
        working-directory: frontend  # Specify the working directory
        run: dart analyze

      - name: Run tests
        working-directory: frontend  # Specify the working directory
        run: dart test
