name: Flutter CI (Frontend)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'  # Specify the desired Flutter SDK version

      - name: Change Directory to Frontend
        run: cd frontend

      - name: Install dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Analyze project source
        working-directory: frontend
        run: |
          flutter analyze --no-pub --fatal-infos --fatal-warnings --fatal-lints || true

      - name: Run tests
        working-directory: frontend
        run: flutter test
